### ISSUE TITLE
Provide a link that could reconstruct the geoeferencing

### ISSUE THREAD

**Issue by arnaldmarcer** [rtdeb/GeoPick#61]
This would be useful for collaboration. However this would need archiving capabilities which were not planned for this kind of tool. However, we can give a thought.

Example: That could be useful for verification/editing (ex: https://www.maps.ie/draw-radius-circle-map/?lat=40.954298290822635&lng=-8.230133056640627&radius=501.3819989059577)

**Comment by arnaldmarcer** [comment]
We can now talk to a database (e.g. postgres). Currently it is being used to control access for those users who want to access the API directly, without the GeoPick UI. These users need authentication, which we solved by registering them in the database and having to authenticate.

We can now use the same access to the database to record the whole georeference, i.e., the same fields that are copied out of GeoPick. Additionally, we will give each georeference a 'geopick_id' which will be able to be used in a call like https://geopick.gbif.org?geopick_id=1234 to retrieve the georeference and even modify it and create a new one. The event to write to the database would be linked to the clicking on the buttons to copy 'with headers' and 'without headers'.

However, this raises the possibility of storing a lot of junk in the database from users who are simply trying the application and digitizing fake georeferences. To avoid this, @aescobarr and @arnaldmarcer propose adding a checkbox 'Share' right above the 'Copy to clipboard' text, which would control whether the georeference is written to the database or not. If checked, the georeference would be stored in the database and the copied csv data would have an additional column with the url to access the georeference (e.g. https://geopick.gbif.org?geopick_id=1234).

Also, we would allow to view a simple point radius if a query is given similar to the www.maps.ie application. For instance, https://geopick.gbif.org?longitude=2&latitude=42&uncertainty=10000 would draw a point at lat,long 42,2 and a circle of radius 10000 around it.

We plan to implement this in the following weeks so that we can also publish it in the publication that is still to be written.

What do you thing @tucotuco and @ArthurChapman ?

**Comment by ArthurChapman** [comment]
This sounds great

I wonder if an addition of a "named place", stored with the shared location, would also be of value (which may even be "20km SE of X"). This would eventually allow for searching of this if someone else had the same locality and lead to (help with) an eventual database of common collecting localities as suggested by @tucotuco

**Comment by arnaldmarcer** [comment]
Yes, that was also the idea, I forgot to mention it. There will be an additional textbox to paste the text of named place.

**Comment by tucotuco** [comment]
Following is just my opinion, obviously. I support the idea of storing feature-only georeferences, but I worry about storing georeferences of other locality types because the interpretation of how it was done is very difficult. With feature-only georeferences, you see directly what the interpretation is and can decide whether to use it. Supporting the other types lends itself to the propagation of unreproducible georeferences. 
In addition, georeferences for many locality types (such as the feature offset heading example Arthur gave) can be reproduced with just the feature georeference. That gets into adding the georeferencing calculator capabilities to GeoPick, which I think would be a better use of effort than supporting georeferences for non-feature-only locality types.

**Comment by arnaldmarcer** [comment]
The problem here lies in that this would imply for GeoPick knowing when it is dealing with a feature-only georeference and that is not easy task. Alternatively, the user could mark the georeference as such, but that would be unreliable and add extra effort. As I see it, it is simply a way for Geopick to provide users the possibility to share their work with others, which could in fact go the other way round, that is, the georeference being seen and validated by more than one person. In fact, this would lead to more homogenization of georeferences (although this would require a very massive use of the application) since some georeferences would not be interpreted differently depending on the user. In the case they were shared they would be consistent one with another. At the end, we can somehow detect 'a posteriori' which are feature-only and only consider them in whatever posterior analysis are done.

We could try to tackle the georeferencing calculator as the next thing.
