### ISSUE TITLE
Display georeference from other source

### ISSUE THREAD

**Issue by tucotuco** [rtdeb/GeoPick#7]
It occurred to me that it would be immensely useful to be able to use the tool to visualize (and edit) georeferences from other sources. I imagine being able to paste an input in any of the supported output formats and be able to see and manipulate it on the map in all the same ways as a georeference created manually with the tool.

This is related to issue #2 because of the support for formats.

**Comment by arnaldmarcer** [comment]
I guess this is covered by the WKT control button, isn't it @tucotuco ?

**Comment by tucotuco** [comment]
That covers the geometries, but it doesn't cover a point-radius.

**Comment by arnaldmarcer** [comment]
The point-radius is covered by the keyboard icon which lets the user enter longitude,latitude and uncertainty.

**Comment by tucotuco** [comment]
Right!

**Comment by arnaldmarcer** [comment]
OK, that settles it, then.

**Comment by arnaldmarcer** [comment]
-
