### ISSUE TITLE
Feature Request: selected named place

### ISSUE THREAD

**Issue by tucotuco** [rtdeb/GeoPick#89]
We are well into georeferencing the African Wild Plants project and one thing that keeps coming up as a useful thing to have is a copy of the named place that was searched for. For example, in the image below, suppose the string for the named place matching the search string is chosen.

<img width="528" alt="image" src="https://github.com/aescobarr/GeoPick/assets/462827/b9da595a-31f4-4532-b2c7-538749f33e4f">

![image](https://github.com/aescobarr/GeoPick/assets/462827/b9da595a-31f4-4532-b2c7-538749f33e4f)

It would be great to have a text box in the results that contained that string, because it is lost as soon as the search is done. That string can be very useful for filling higher geography and even for building a reference gazetteer of places to accompany a dataset.  I would not include this string in the data that are copied for the georeference, but I would have the text be copiable.

**Comment by tucotuco** [comment]
The request is to have the entire latest selected string from the search box go into an info box from which it could be copied. It should not go into the exported results. The label, to be clear, could be something like, "Latest search". It would have no Darwin Core link. This combination, plus an explanation in help, could be enough to avoid confusion.

**Comment by arnaldmarcer** [comment]
What about something like this, @tucotuco
![image](https://github.com/aescobarr/GeoPick/assets/15831763/c2e5b256-0777-48fa-898d-9084a5c06308)

**Comment by tucotuco** [comment]
I like it!
